dinnerA = [['Kevin Rosa', '../static/Prefrosh/RosaKevin.JPG'], ['Yoojin Chung', '../static/Prefrosh/ChungYoojin.JPG'], ['June Kim', '../static/Prefrosh/KimJooEun.JPG'], ['Rachel Lin', '../static/Prefrosh/LinRachel.JPG'], ['Neymika Jain', '../static/Prefrosh/JainNeymika.JPG'], ['Lyn Li', '../static/Prefrosh/LiChenyue.JPG'], ['Louie Santos', '../static/Prefrosh/SantosLouis.JPG'], ['David Wu', '../static/Prefrosh/WuDavid.JPG'], ['Alex Janosi', '../static/Prefrosh/JanosiAlex.JPG'], ['Matthew Alexander', '../static/Prefrosh/AlexanderMatthew.JPG'], ['Emma Qian', '../static/Prefrosh/QianHanmin.JPG'], ['Mitchell Watson', '../static/Prefrosh/WatsonMitchell.JPG'], ['Arushi Gupta', '../static/Prefrosh/GuptaArushi.JPG'], ['Ishani Karmarkar', '../static/Prefrosh/KarmarkarIshani.JPG'], ['Netra Ravishankar', '../static/Prefrosh/RavishankarNetra.JPG'], ['Cole Brabec', '../static/Prefrosh/BrabecCole.JPG'], ['Andrew Hess', '../static/Prefrosh/HessAndrew.JPG'], ['Nick Clausen', '../static/Prefrosh/ClausenNicholas.JPG'], ['Sarah Guenov', '../static/Prefrosh/GuenovSarah.JPG'], ['Kenyon Prater', '../static/Prefrosh/PraterKenyon.JPG'], ['Alice Jin', '../static/Prefrosh/JinQixuan.JPG'], ['Su Min Lee', '../static/Prefrosh/LeeSuMin.JPG'], ['Regina Lee', '../static/Prefrosh/LeeRegina.JPG'], ['Rosita Fu', '../static/Prefrosh/FuRosita.JPG'], ['Anjali Patil', '../static/Prefrosh/PatilAnjali.JPG'], ['Jack Maxfield', '../static/Prefrosh/MaxfieldJack.JPG'], ['Christine Yu', '../static/Prefrosh/YuChristine.JPG'], ['Krystyna Maruszko', '../static/Prefrosh/MaruszkoKrystyna.JPG'], ['Andrew Chan', '../static/Prefrosh/ChanAndrew.JPG'], ['Frank Kou', '../static/Prefrosh/KouFrank.JPG'], ['Maquelle Tiffany', '../static/Prefrosh/TiffanyMaquelle.JPG']]

dinnerB = [['Luke Blankenberg', '../static/Prefrosh/BlankenbergLuke.JPG'], ['Tony Kukavica', '../static/Prefrosh/KukavicaAnthony.JPG'], ['Ashima Agarwal', '../static/Prefrosh/AgarwalAshima.JPG'], ['Angelina Ye', '../static/Prefrosh/YeAngelina.JPG'], ['Brittany Wylie', '../static/Prefrosh/WylieBrittany.JPG'], ['Lucy Chen', '../static/Prefrosh/ChenLucy.JPG'], ['Mohith Manohara', '../static/Prefrosh/ManoharaMohith.JPG'], ['Alessio Amaolo', '../static/Prefrosh/AmaoloAlessio.JPG'], ['Noah Sock', '../static/Prefrosh/SockNoah.JPG'], ['Akshay Yeluri', '../static/Prefrosh/YeluriAkshay.JPG'], ['James Park', '../static/Prefrosh/ParkJames.JPG'], ['Katie Wong', '../static/Prefrosh/WongKatie.JPG'], ['Neil Sanderson', '../static/Prefrosh/SandersonNeil.JPG'], ['Jacob Snyder', '../static/Prefrosh/SnyderJacob.JPG'], ['Kristine Chelakkat', '../static/Prefrosh/ChelakkatKristine.JPG'], ['Jagath Vytheeswaran', '../static/Prefrosh/VytheeswaranJagath.JPG'], ['Kevin Yu', '../static/Prefrosh/YuKevin.JPG'], ['Albert Nazeeri', '../static/Prefrosh/NazeeriAlbert.JPG'], ['John Wang', '../static/Prefrosh/WangJohn.JPG'], ['Sanjana Kulkarni', '../static/Prefrosh/KulkarniSanjana.JPG'], ['Maya Mutic', '../static/Prefrosh/MuticMaya.JPG'], ['Rachel Shi', '../static/Prefrosh/ShiRachel.JPG'], ['Mai Nguyen', '../static/Prefrosh/NguyenMai.JPG'], ['Rachel Sun', '../static/Prefrosh/SunRachel.JPG'], ['Emily Thierstein', '../static/Prefrosh/ThiersteinEmily.JPG'], ['Alfred Joseph', '../static/Prefrosh/JosephAlfred.JPG'], ['Vivian Yu', '../static/Prefrosh/YuQiyao.JPG'], ['Andy Rothstein', '../static/Prefrosh/RothsteinAndrew.JPG'], ['Richard Dargan', '../static/Prefrosh/DarganRichard.JPG'], ['Kushal Tirumala', '../static/Prefrosh/TirumalaKushal.JPG'], ['Matt Riker', '../static/Prefrosh/RikerMatthew.JPG'], ['Gabriel Woolls', '../static/Prefrosh/WoollsGabriel.JPG'], ['Sarina Liu', '../static/Prefrosh/LiuSarina.JPG']]

dinnerC = [['Erika Yu', '../static/Prefrosh/YuShuyue.JPG'], ['Sergio Escobar', '../static/Prefrosh/EscobarSergio.JPG'], ['Erich Liang', '../static/Prefrosh/LiangErich.JPG'], ['Vignesh Varadarajan', '../static/Prefrosh/VaradarajanVignesh.JPG'], ['Gokul Srinivasaragavan', '../static/Prefrosh/SrinivasaragavanGokul.JPG'], ['Jacob Ressler-Craig', '../static/Prefrosh/Ressler-CraigJacob.JPG'], ['Ethan Jaszewski', '../static/Prefrosh/JaszewskiEthan.JPG'], ['Vidhya Dev', '../static/Prefrosh/DevVidhya.JPG'], ['Jessica Sun', '../static/Prefrosh/SunJessica.JPG'], ['Nora Griffith', '../static/Prefrosh/GriffithNora.JPG'], ['Stella Wang', '../static/Prefrosh/WangStella.JPG'], ['Galileo Resca-Candini', '../static/Prefrosh/Resca-CandiniGalileo.JPG'], ['Eric Moreno', '../static/Prefrosh/MorenoEric.JPG'], ['Chad Thut', '../static/Prefrosh/ThutCharles.JPG'], ['Shu Fay Ung', '../static/Prefrosh/UngShuFay.JPG'], ['John Shang', '../static/Prefrosh/ShangZhengyuan.JPG'], ['Nathaniel Smith', '../static/Prefrosh/SmithNathaniel.JPG'], ['Sharne Sun', '../static/Prefrosh/SunSharne.JPG'], ['Dan Rostovtsev', '../static/Prefrosh/RostovtsevDaniel.JPG'], ['Karena Chow', '../static/Prefrosh/ChowKarena.JPG'], ['Sara Fish', '../static/Prefrosh/FishSara.JPG'], ['Ola Kalisz', '../static/Prefrosh/KaliszAleksandra.JPG'], ['Kali Drango', '../static/Prefrosh/DrangoKaliden.JPG'], ['Adam Kogan', '../static/Prefrosh/KoganAdam.JPG'], ['Anirudh Rangaswamy', '../static/Prefrosh/RangaswamyAnirudh.JPG'], ['Vivienne Patwardhan', '../static/Prefrosh/PatwardhanVivienne.JPG'], ['Esther Kim', '../static/Prefrosh/KimEsther.JPG'], ['Tina Zhang', '../static/Prefrosh/ZhangYantian.JPG'], ['Dominic Catanzaro', '../static/Prefrosh/CatanzaroDominic.JPG'], ['Tara Porter', '../static/Prefrosh/PorterTara.JPG'], ['Brendan Berrigan', '../static/Prefrosh/BerriganBrendan.JPG']]

linnerD = [['Amol Patil', '../static/Prefrosh/PatilAmol.JPG'], ['Daniel Kim', '../static/Prefrosh/KimDaniel.JPG'], ['Yuanzhe Xie', '../static/Prefrosh/XieYuanzhe.JPG'], ['Ankita Roychoudhury', '../static/Prefrosh/RoychoudhuryAnkita.JPG'], ['Spencer Schneider', '../static/Prefrosh/SchneiderSpencer.JPG'], ['Eunice Yoon', '../static/Prefrosh/YoonEunice.JPG'], ['Krystal Brodsky', '../static/Prefrosh/BrodskyKrystal.JPG'], ['Hao Qi', '../static/Prefrosh/QiZihao.JPG'], ['Irene Crowell', '../static/Prefrosh/CrowellIrene.JPG'], ['Cindy Cao', '../static/Prefrosh/CaoSiting.JPG'], ['Kriti Devasenapathy', '../static/Prefrosh/DevasenapathyKiruthika.JPG'], ['Steven Csaposs', '../static/Prefrosh/CsapossSteven.JPG'], ['Sam Owen', '../static/Prefrosh/OwenSamuel.JPG'], ['Qingzhou Aw Young', '../static/Prefrosh/AwYoungQingzhou.JPG'], ['Anthony Bao', '../static/Prefrosh/BaoAnthony.JPG'], ['JD Walker', '../static/Prefrosh/WalkerJames.JPG'], ['XinYi Ren', '../static/Prefrosh/RenXinYi.JPG'], ['Rahul Arun', '../static/Prefrosh/ArunRahul.JPG'], ['Jessica Ye', '../static/Prefrosh/YeJessica.JPG'], ['Elaine Lowinger', '../static/Prefrosh/LowingerElaine.JPG'], ['Hao Sun', '../static/Prefrosh/SunHaoyuan.JPG'], ['Ankush Hommerich-Dutt', '../static/Prefrosh/Hommerich-DuttAnkush.JPG'], ['Julian Sanders', '../static/Prefrosh/SandersJulian.JPG'], ['James Jusuf', '../static/Prefrosh/JusufJames.JPG'], ['Reggy Granovskiy', '../static/Prefrosh/GranovskiyRebecca.JPG'], ['Molly Crotteau', '../static/Prefrosh/CrotteauMolly.JPG'], ['Gian de Castro', '../static/Prefrosh/deCastroGianfranco.JPG'], ['Nerys Huffman', '../static/Prefrosh/HuffmanNerys.JPG'], ['Michael Yao', '../static/Prefrosh/YaoMichael.JPG'], ['Sirisha Gudavalli', '../static/Prefrosh/GudavalliSirisha.JPG'], ['Brandon Quach', '../static/Prefrosh/QuachBrandon.JPG']]

dinnerE = [['Hyerin Cho', '../static/Prefrosh/ChoHyerin.JPG'], ['Andrew Zhou', '../static/Prefrosh/ZhouAndrew.JPG'], ['Lauren Liu', '../static/Prefrosh/LiuLauren.JPG'], ['Malia Rebollo', '../static/Prefrosh/RebolloMalia.JPG'], ['Eric Chen', '../static/Prefrosh/ChenEric.JPG'], ['Mark Xu', '../static/Prefrosh/XuMark.JPG'], ['Tarini Singh', '../static/Prefrosh/SinghTarini.JPG'], ['Christie Huang', '../static/Prefrosh/HuangChristie.JPG'], ['Claire Hu', '../static/Prefrosh/HuXinyue.JPG'], ['Sherry Liang', '../static/Prefrosh/LiangXueer.JPG'], ['Amy Wang', '../static/Prefrosh/WangAmy.JPG'], ['Tynesha Pham', '../static/Prefrosh/PhamTynesha.JPG'], ['Logan Apple', '../static/Prefrosh/AppleLogan.JPG'], ['Hongsen Qin', '../static/Prefrosh/QinHongsen.JPG'], ['Andrea Hands Arocha', '../static/Prefrosh/HandsArochaAndrea.JPG'], ['Daniel Zhou', '../static/Prefrosh/ZhouDaniel.JPG'], ['Dawn Tang', '../static/Prefrosh/TangYuchen.JPG'], ['Vinayak Kumar', '../static/Prefrosh/KumarVinayak.JPG'], ['Andrew Ho', '../static/Prefrosh/HoAndrew.JPG'], ['Jethin Gowda', '../static/Prefrosh/GowdaJethin.JPG'], ['Albert Tseng', '../static/Prefrosh/TsengAlbert.JPG'], ['Hale Obernolte', '../static/Prefrosh/ObernolteHale.JPG'], ['Liana Merk', '../static/Prefrosh/MerkLiana.JPG'], ['Marcus Gee', '../static/Prefrosh/GeeMarcus.JPG'], ['Alexei Garcia', '../static/Prefrosh/GarciaAlexei.JPG'], ['Amritpal Singh', '../static/Prefrosh/SinghAmritpal.JPG']]

linnerF = [['Yu Jin Kim', '../static/Prefrosh/KimYuJin.JPG'], ['Aileen Zhang', '../static/Prefrosh/ZhangYuling.JPG'], ['Laura Hu', '../static/Prefrosh/HuLaura.JPG'], ['Mike Iovine', '../static/Prefrosh/IovineMichael.JPG'], ['Varun Shanker', '../static/Prefrosh/ShankerVarun.JPG'], ['James Wei', '../static/Prefrosh/WeiJames.JPG'], ['Ethan Ordentlich', '../static/Prefrosh/OrdentlichEthan.JPG'], ['Lily Kitagawa', '../static/Prefrosh/KitagawaLily.JPG'], ['Ari Rosner', '../static/Prefrosh/RosnerAriel.JPG'], ['Rahil Bathwal', '../static/Prefrosh/BathwalRahil.JPG'], ['Riana Karim', '../static/Prefrosh/KarimRiana.JPG'], ['Jeremiah Dibble', '../static/Prefrosh/DibbleJeremiah.JPG'], ['Shiva Mudide', '../static/Prefrosh/MudideShiva.JPG'], ['Steve Guo', '../static/Prefrosh/GuoSteve.JPG'], ['Isabella Zhang', '../static/Prefrosh/ZhangIsabella.JPG'], ['Ali Boubezari', '../static/Prefrosh/BoubezariAli.JPG'], ['Eric Han', '../static/Prefrosh/HanEric.JPG'], ['Davis Tardif', '../static/Prefrosh/TardifDavis.JPG'], ['Lexy LeMar', '../static/Prefrosh/LeMarLexy.JPG'], ['Arundhati Mukherjea', '../static/Prefrosh/MukherjeaArundhati.JPG'], ['Mahi Gokuli', '../static/Prefrosh/GokuliMahi.JPG'], ['Tomek Andrzejewski', '../static/Prefrosh/AndrzejewskiTomasz.JPG'], ['Krystin Brown', '../static/Prefrosh/BrownKrystin.JPG'], ['Kevin Winzey', '../static/Prefrosh/WinzeyKevin.JPG'], ['Spencer Morgenfeld', '../static/Prefrosh/MorgenfeldSpencer.JPG'], ['Allyson Trussell', '../static/Prefrosh/TrussellAllyson.JPG'], ['Alveera Khan', '../static/Prefrosh/KhanAlveera.JPG'], ['Daniel Neamati', '../static/Prefrosh/NeamatiDaniel.JPG'], ['Maheck Jerez Terceros', '../static/Prefrosh/JerezTercerosMaheck.JPG'], ['Jae Kang', '../static/Prefrosh/KangJaeyoung.JPG']]

dinnerG = [['Nayla Abney', '../static/Prefrosh/AbneyNayla.JPG'], ['Natalie Yao', '../static/Prefrosh/YaoLeyu.JPG'], ['Alycia Lee', '../static/Prefrosh/LeeAlycia.JPG'], ['Olivia Durrett', '../static/Prefrosh/DurrettOlivia.JPG'], ['Yelim Lee', '../static/Prefrosh/LeeYelim.JPG'], ['John Heath', '../static/Prefrosh/HeathJohn.JPG'], ['Nicholas Ardavin', '../static/Prefrosh/ArdavinNicholas.JPG'], ['Dillon Holder', '../static/Prefrosh/HolderLofton.JPG'], ['Galilea von Ruden', '../static/Prefrosh/vonRudenGalilea.JPG'], ['Shirley Zhu', '../static/Prefrosh/ZhuShiyun.JPG'], ['Victoria Su', '../static/Prefrosh/SuVictoria.JPG'], ['Mayank Pandey', '../static/Prefrosh/PandeyMayank.JPG'], ['Michael Brown', '../static/Prefrosh/BrownMichael.JPG'], ['Reimond Costa', '../static/Prefrosh/CostaReimond.JPG'], ['Katrina Korovina', '../static/Prefrosh/KorovinaEkaterina.JPG'], ['LC Chen', '../static/Prefrosh/ChenLC.JPG'], ['Richard Bao', '../static/Prefrosh/BaoRichard.JPG'], ['Matt Zeitlin', '../static/Prefrosh/ZeitlinMatthew.JPG'], ['Jamie Vinson', '../static/Prefrosh/VinsonJamie.JPG'], ['Amanda Li', '../static/Prefrosh/LiAmanda.JPG'], ['Tegan Loveridge', '../static/Prefrosh/LoveridgeTegan.JPG'], ['Rohan Mirchandani', '../static/Prefrosh/MirchandaniRohan.JPG'], ['Matthew Kim', '../static/Prefrosh/KimMinHyuk.JPG'], ['Albert Zhai', '../static/Prefrosh/ZhaiAlbert.JPG'], ['Catrin Murphy', '../static/Prefrosh/MurphyCatrin.JPG'], ['Thomas Kwa', '../static/Prefrosh/KwaThomas.JPG'], ['Andrew Larson', '../static/Prefrosh/LarsonAndrew.JPG'], ['Maya Srikanth', '../static/Prefrosh/SrikanthMaya.JPG'], ['Sarida Pratuangtham', '../static/Prefrosh/PratuangthamSarida.JPG'], ['Vandana Agarwala', '../static/Prefrosh/AgarwalaVandana.JPG']]

dinnerH = [['Alexander Zlokapa', '../static/Prefrosh/ZlokapaAlexander.JPG'], ['Kasey Adams', '../static/Prefrosh/AdamsKasey.JPG'], ['Ruoyun Zheng', '../static/Prefrosh/ZhengRuoyun.JPG'], ['Joe Como', '../static/Prefrosh/ComoJoseph.JPG'], ['Alex Guerra', '../static/Prefrosh/GuerraAlex.JPG'], ['David Zheng', '../static/Prefrosh/ZhengDavid.JPG'], ['Aditi Shankar', '../static/Prefrosh/ShankarAditi.JPG'], ['Jose Proskauer', '../static/Prefrosh/ProskauerJose.JPG'], ['Daniel Delgado', '../static/Prefrosh/DelgadoDaniel.JPG'], ['Zimo Zhu', '../static/Prefrosh/ZhuZimo.JPG'], ['Izzy Muise', '../static/Prefrosh/MuiseIsabelle.JPG'], ['Johanna Karras', '../static/Prefrosh/KarrasJohanna.JPG'], ['Ruy Gonzalez Hermosillo', '../static/Prefrosh/GonzalezHermosilloRuy.JPG'], ['Roby Joseph', '../static/Prefrosh/JosephRoby.JPG'], ['Lauren Suezaki', '../static/Prefrosh/SuezakiLauren.JPG'], ['Grace Ding', '../static/Prefrosh/DingGrace.JPG'], ['Nicholas Currault', '../static/Prefrosh/CurraultDouglas.JPG'], ['Nora Koe', '../static/Prefrosh/KoeNora.JPG'], ['Ryan Han', '../static/Prefrosh/HanRyan.JPG'], ['Paulina Ridland', '../static/Prefrosh/RidlandPaulina.JPG'], ['Caleb Sander', '../static/Prefrosh/SanderCaleb.JPG'], ['Ryan White', '../static/Prefrosh/WhiteRyan.JPG'], ['Matthew Earney', '../static/Prefrosh/EarneyMatthew.JPG'], ['Donovan Ye', '../static/Prefrosh/YeDonovan.JPG'], ['Whitney Sloneker', '../static/Prefrosh/SlonekerWhitney.JPG'], ['Pavan Chitta', '../static/Prefrosh/ChittaPavan.JPG'], ['Isabella Camplisson', '../static/Prefrosh/CamplissonIsabella.JPG'], ['Alexander Popov', '../static/Prefrosh/PopovAlexander.JPG']]

dessert1 = [['Mike Iovine', '../static/Prefrosh/IovineMichael.JPG'], ['Ankita Roychoudhury', '../static/Prefrosh/RoychoudhuryAnkita.JPG'], ['Olivia Durrett', '../static/Prefrosh/DurrettOlivia.JPG'], ['Lily Kitagawa', '../static/Prefrosh/KitagawaLily.JPG'], ['Eunice Yoon', '../static/Prefrosh/YoonEunice.JPG'], ['Christie Huang', '../static/Prefrosh/HuangChristie.JPG'], ['Hao Qi', '../static/Prefrosh/QiZihao.JPG'], ['Dillon Holder', '../static/Prefrosh/HolderLofton.JPG'], ['Shiva Mudide', '../static/Prefrosh/MudideShiva.JPG'], ['Anthony Bao', '../static/Prefrosh/BaoAnthony.JPG'], ['JD Walker', '../static/Prefrosh/WalkerJames.JPG'], ['LC Chen', '../static/Prefrosh/ChenLC.JPG'], ['Sanjana Kulkarni', '../static/Prefrosh/KulkarniSanjana.JPG'], ['Elaine Lowinger', '../static/Prefrosh/LowingerElaine.JPG'], ['Ankush Hommerich-Dutt', '../static/Prefrosh/Hommerich-DuttAnkush.JPG'], ['Maya Mutic', '../static/Prefrosh/MuticMaya.JPG'], ['Julian Sanders', '../static/Prefrosh/SandersJulian.JPG'], ['Rachel Shi', '../static/Prefrosh/ShiRachel.JPG'], ['Reggy Granovskiy', '../static/Prefrosh/GranovskiyRebecca.JPG'], ['Dawn Tang', '../static/Prefrosh/TangYuchen.JPG'], ['Emily Thierstein', '../static/Prefrosh/ThiersteinEmily.JPG'], ['Vinayak Kumar', '../static/Prefrosh/KumarVinayak.JPG'], ['Vivienne Patwardhan', '../static/Prefrosh/PatwardhanVivienne.JPG'], ['Allyson Trussell', '../static/Prefrosh/TrussellAllyson.JPG'], ['Tegan Loveridge', '../static/Prefrosh/LoveridgeTegan.JPG'], ['Esther Kim', '../static/Prefrosh/KimEsther.JPG'], ['Albert Tseng', '../static/Prefrosh/TsengAlbert.JPG'], ['Nerys Huffman', '../static/Prefrosh/HuffmanNerys.JPG'], ['Dominic Catanzaro', '../static/Prefrosh/CatanzaroDominic.JPG'], ['Michael Yao', '../static/Prefrosh/YaoMichael.JPG'], ['Kushal Tirumala', '../static/Prefrosh/TirumalaKushal.JPG'], ['Andrew Larson', '../static/Prefrosh/LarsonAndrew.JPG'], ['Pavan Chitta', '../static/Prefrosh/ChittaPavan.JPG'], ['Isabella Camplisson', '../static/Prefrosh/CamplissonIsabella.JPG'], ['Jae Kang', '../static/Prefrosh/KangJaeyoung.JPG'], ['Amritpal Singh', '../static/Prefrosh/SinghAmritpal.JPG']]

dessert2 = [['Erika Yu', '../static/Prefrosh/YuShuyue.JPG'], ['Nayla Abney', '../static/Prefrosh/AbneyNayla.JPG'], ['Kasey Adams', '../static/Prefrosh/AdamsKasey.JPG'], ['Amol Patil', '../static/Prefrosh/PatilAmol.JPG'], ['Malia Rebollo', '../static/Prefrosh/RebolloMalia.JPG'], ['Yuanzhe Xie', '../static/Prefrosh/XieYuanzhe.JPG'], ['David Zheng', '../static/Prefrosh/ZhengDavid.JPG'], ['Vidhya Dev', '../static/Prefrosh/DevVidhya.JPG'], ['Aditi Shankar', '../static/Prefrosh/ShankarAditi.JPG'], ['Jose Proskauer', '../static/Prefrosh/ProskauerJose.JPG'], ['Spencer Schneider', '../static/Prefrosh/SchneiderSpencer.JPG'], ['Ethan Ordentlich', '../static/Prefrosh/OrdentlichEthan.JPG'], ['Yelim Lee', '../static/Prefrosh/LeeYelim.JPG'], ['John Heath', '../static/Prefrosh/HeathJohn.JPG'], ['Daniel Delgado', '../static/Prefrosh/DelgadoDaniel.JPG'], ['Nora Griffith', '../static/Prefrosh/GriffithNora.JPG'], ['Nicholas Ardavin', '../static/Prefrosh/ArdavinNicholas.JPG'], ['Krystal Brodsky', '../static/Prefrosh/BrodskyKrystal.JPG'], ['Riana Karim', '../static/Prefrosh/KarimRiana.JPG'], ['Irene Crowell', '../static/Prefrosh/CrowellIrene.JPG'], ['Steve Guo', '../static/Prefrosh/GuoSteve.JPG'], ['Qingzhou Aw Young', '../static/Prefrosh/AwYoungQingzhou.JPG'], ['Logan Apple', '../static/Prefrosh/AppleLogan.JPG'], ['Nicholas Currault', '../static/Prefrosh/CurraultDouglas.JPG'], ['Andrea Hands Arocha', '../static/Prefrosh/HandsArochaAndrea.JPG'], ['Tomek Andrzejewski', '../static/Prefrosh/AndrzejewskiTomasz.JPG'], ['Richard Bao', '../static/Prefrosh/BaoRichard.JPG'], ['Matt Zeitlin', '../static/Prefrosh/ZeitlinMatthew.JPG'], ['Ryan Han', '../static/Prefrosh/HanRyan.JPG'], ['Paulina Ridland', '../static/Prefrosh/RidlandPaulina.JPG'], ['Matthew Earney', '../static/Prefrosh/EarneyMatthew.JPG'], ['Jamie Vinson', '../static/Prefrosh/VinsonJamie.JPG'], ['Amanda Li', '../static/Prefrosh/LiAmanda.JPG'], ['Jethin Gowda', '../static/Prefrosh/GowdaJethin.JPG'], ['Hale Obernolte', '../static/Prefrosh/ObernolteHale.JPG'], ['Maya Srikanth', '../static/Prefrosh/SrikanthMaya.JPG']]

dessert3 = [['Alexander Zlokapa', '../static/Prefrosh/ZlokapaAlexander.JPG'], ['Sergio Escobar', '../static/Prefrosh/EscobarSergio.JPG'], ['Ruoyun Zheng', '../static/Prefrosh/ZhengRuoyun.JPG'], ['Aileen Zhang', '../static/Prefrosh/ZhangYuling.JPG'], ['James Wei', '../static/Prefrosh/WeiJames.JPG'], ['Ashima Agarwal', '../static/Prefrosh/AgarwalAshima.JPG'], ['Angelina Ye', '../static/Prefrosh/YeAngelina.JPG'], ['Alycia Lee', '../static/Prefrosh/LeeAlycia.JPG'], ['Ari Rosner', '../static/Prefrosh/RosnerAriel.JPG'], ['Jeremiah Dibble', '../static/Prefrosh/DibbleJeremiah.JPG'], ['Alessio Amaolo', '../static/Prefrosh/AmaoloAlessio.JPG'], ['Zimo Zhu', '../static/Prefrosh/ZhuZimo.JPG'], ['Kristine Chelakkat', '../static/Prefrosh/ChelakkatKristine.JPG'], ['Kevin Yu', '../static/Prefrosh/YuKevin.JPG'], ['Allessandra Mondello', '../static/Prefrosh/MondelloAllessandra.JPG'], ['Albert Nazeeri', '../static/Prefrosh/NazeeriAlbert.JPG'], ['Arundhati Mukherjea', '../static/Prefrosh/MukherjeaArundhati.JPG'], ['Nora Koe', '../static/Prefrosh/KoeNora.JPG'], ['Rachel Sun', '../static/Prefrosh/SunRachel.JPG'], ['Donovan Ye', '../static/Prefrosh/YeDonovan.JPG'], ['Rohan Mirchandani', '../static/Prefrosh/MirchandaniRohan.JPG'], ['Matthew Kim', '../static/Prefrosh/KimMinHyuk.JPG'], ['Alfred Joseph', '../static/Prefrosh/JosephAlfred.JPG'], ['Andy Rothstein', '../static/Prefrosh/RothsteinAndrew.JPG'], ['Alveera Khan', '../static/Prefrosh/KhanAlveera.JPG'], ['Tara Porter', '../static/Prefrosh/PorterTara.JPG'], ['Sarina Liu', '../static/Prefrosh/LiuSarina.JPG']]

dessert4 = [['Hyerin Cho', '../static/Prefrosh/ChoHyerin.JPG'], ['Erich Liang', '../static/Prefrosh/LiangErich.JPG'], ['Natalie Yao', '../static/Prefrosh/YaoLeyu.JPG'], ['Gokul Srinivasaragavan', '../static/Prefrosh/SrinivasaragavanGokul.JPG'], ['Joe Como', '../static/Prefrosh/ComoJoseph.JPG'], ['Eric Chen', '../static/Prefrosh/ChenEric.JPG'], ['Mark Xu', '../static/Prefrosh/XuMark.JPG'], ['Galilea von Ruden', '../static/Prefrosh/vonRudenGalilea.JPG'], ['Galileo Resca-Candini', '../static/Prefrosh/Resca-CandiniGalileo.JPG'], ['Mohith Manohara', '../static/Prefrosh/ManoharaMohith.JPG'], ['Victoria Su', '../static/Prefrosh/SuVictoria.JPG'], ['Tynesha Pham', '../static/Prefrosh/PhamTynesha.JPG'], ['Katrina Korovina', '../static/Prefrosh/KorovinaEkaterina.JPG'], ['Sara Fish', '../static/Prefrosh/FishSara.JPG'], ['XinYi Ren', '../static/Prefrosh/RenXinYi.JPG'], ['Rahul Arun', '../static/Prefrosh/ArunRahul.JPG'], ['Daniel Zhou', '../static/Prefrosh/ZhouDaniel.JPG'], ['Kali Drango', '../static/Prefrosh/DrangoKaliden.JPG'], ['Adam Kogan', '../static/Prefrosh/KoganAdam.JPG'], ['James Jusuf', '../static/Prefrosh/JusufJames.JPG'], ['Mai Nguyen', '../static/Prefrosh/NguyenMai.JPG'], ['Ryan White', '../static/Prefrosh/WhiteRyan.JPG'], ['Andrew Ho', '../static/Prefrosh/HoAndrew.JPG'], ['Whitney Sloneker', '../static/Prefrosh/SlonekerWhitney.JPG'], ['Albert Zhai', '../static/Prefrosh/ZhaiAlbert.JPG'], ['Richard Dargan', '../static/Prefrosh/DarganRichard.JPG'], ['Catrin Murphy', '../static/Prefrosh/MurphyCatrin.JPG'], ['Matt Riker', '../static/Prefrosh/RikerMatthew.JPG'], ['Sirisha Gudavalli', '../static/Prefrosh/GudavalliSirisha.JPG'], ['Gabriel Woolls', '../static/Prefrosh/WoollsGabriel.JPG']]

dessert5 = [['Andrew Zhou', '../static/Prefrosh/ZhouAndrew.JPG'], ['Lauren Liu', '../static/Prefrosh/LiuLauren.JPG'], ['Vignesh Varadarajan', '../static/Prefrosh/VaradarajanVignesh.JPG'], ['Jacob Ressler-Craig', '../static/Prefrosh/Ressler-CraigJacob.JPG'], ['Alex Guerra', '../static/Prefrosh/GuerraAlex.JPG'], ['Laura Hu', '../static/Prefrosh/HuLaura.JPG'], ['Ethan Jaszewski', '../static/Prefrosh/JaszewskiEthan.JPG'], ['Varun Shanker', '../static/Prefrosh/ShankerVarun.JPG'], ['Jessica Sun', '../static/Prefrosh/SunJessica.JPG'], ['Rahil Bathwal', '../static/Prefrosh/BathwalRahil.JPG'], ['Stella Wang', '../static/Prefrosh/WangStella.JPG'], ['Lucy Chen', '../static/Prefrosh/ChenLucy.JPG'], ['Claire Hu', '../static/Prefrosh/HuXinyue.JPG'], ['Hongsen Qin', '../static/Prefrosh/QinHongsen.JPG'], ['John Wang', '../static/Prefrosh/WangJohn.JPG'], ['Jessica Ye', '../static/Prefrosh/YeJessica.JPG'], ['Lauren Suezaki', '../static/Prefrosh/SuezakiLauren.JPG'], ['Grace Ding', '../static/Prefrosh/DingGrace.JPG'], ['Mahi Gokuli', '../static/Prefrosh/GokuliMahi.JPG'], ['Ola Kalisz', '../static/Prefrosh/KaliszAleksandra.JPG'], ['Caleb Sander', '../static/Prefrosh/SanderCaleb.JPG'], ['Krystin Brown', '../static/Prefrosh/BrownKrystin.JPG'], ['Molly Crotteau', '../static/Prefrosh/CrotteauMolly.JPG'], ['Timur Kuzhagaliyev', '../static/Prefrosh/KuzhagaliyevTimur.JPG'], ['Liana Merk', '../static/Prefrosh/MerkLiana.JPG'], ['Daniel Neamati', '../static/Prefrosh/NeamatiDaniel.JPG'], ['Alexei Garcia', '../static/Prefrosh/GarciaAlexei.JPG'], ['Brandon Quach', '../static/Prefrosh/QuachBrandon.JPG'], ['Alexander Popov', '../static/Prefrosh/PopovAlexander.JPG']]

dessert6 = [['Yu Jin Kim', '../static/Prefrosh/KimYuJin.JPG'], ['Daniel Kim', '../static/Prefrosh/KimDaniel.JPG'], ['Luke Blankenberg', '../static/Prefrosh/BlankenbergLuke.JPG'], ['Tarini Singh', '../static/Prefrosh/SinghTarini.JPG'], ['Brittany Wylie', '../static/Prefrosh/WylieBrittany.JPG'], ['Shirley Zhu', '../static/Prefrosh/ZhuShiyun.JPG'], ['Noah Sock', '../static/Prefrosh/SockNoah.JPG'], ['Isabella Zhang', '../static/Prefrosh/ZhangIsabella.JPG'], ['Karena Chow', '../static/Prefrosh/ChowKarena.JPG'], ['Jagath Vytheeswaran', '../static/Prefrosh/VytheeswaranJagath.JPG'], ['Lexy LeMar', '../static/Prefrosh/LeMarLexy.JPG'], ['Hao Sun', '../static/Prefrosh/SunHaoyuan.JPG'], ['Anirudh Rangaswamy', '../static/Prefrosh/RangaswamyAnirudh.JPG'], ['Kevin Winzey', '../static/Prefrosh/WinzeyKevin.JPG'], ['Spencer Morgenfeld', '../static/Prefrosh/MorgenfeldSpencer.JPG'], ['Tina Zhang', '../static/Prefrosh/ZhangYantian.JPG'], ['Gian de Castro', '../static/Prefrosh/deCastroGianfranco.JPG'], ['Vivian Yu', '../static/Prefrosh/YuQiyao.JPG'], ['Marcus Gee', '../static/Prefrosh/GeeMarcus.JPG'], ['Maheck Jerez Terceros', '../static/Prefrosh/JerezTercerosMaheck.JPG'], ['Thomas Kwa', '../static/Prefrosh/KwaThomas.JPG'], ['Brendan Berrigan', '../static/Prefrosh/BerriganBrendan.JPG'], ['Sarida Pratuangtham', '../static/Prefrosh/PratuangthamSarida.JPG'], ['Vandana Agarwala', '../static/Prefrosh/AgarwalaVandana.JPG']]

dessert7 = [['Cindy Cao', '../static/Prefrosh/CaoSiting.JPG'], ['Eric Moreno', '../static/Prefrosh/MorenoEric.JPG'], ['Sherry Liang', '../static/Prefrosh/LiangXueer.JPG'], ['Izzy Muise', '../static/Prefrosh/MuiseIsabelle.JPG'], ['Chad Thut', '../static/Prefrosh/ThutCharles.JPG'], ['Shu Fay Ung', '../static/Prefrosh/UngShuFay.JPG'], ['Isabell Yang', '../static/Prefrosh/YangIsabell.JPG'], ['Amy Wang', '../static/Prefrosh/WangAmy.JPG'], ['Kriti Devasenapathy', '../static/Prefrosh/DevasenapathyKiruthika.JPG'], ['John Shang', '../static/Prefrosh/ShangZhengyuan.JPG'], ['Akshay Yeluri', '../static/Prefrosh/YeluriAkshay.JPG'], ['Ali Boubezari', '../static/Prefrosh/BoubezariAli.JPG'], ['Johanna Karras', '../static/Prefrosh/KarrasJohanna.JPG'], ['Steven Csaposs', '../static/Prefrosh/CsapossSteven.JPG'], ['Eric Han', '../static/Prefrosh/HanEric.JPG'], ['James Park', '../static/Prefrosh/ParkJames.JPG'], ['Katie Wong', '../static/Prefrosh/WongKatie.JPG'], ['Mayank Pandey', '../static/Prefrosh/PandeyMayank.JPG'], ['Ruy Gonzalez Hermosillo', '../static/Prefrosh/GonzalezHermosilloRuy.JPG'], ['Sam Owen', '../static/Prefrosh/OwenSamuel.JPG'], ['Neil Sanderson', '../static/Prefrosh/SandersonNeil.JPG'], ['Michael Brown', '../static/Prefrosh/BrownMichael.JPG'], ['Jacob Snyder', '../static/Prefrosh/SnyderJacob.JPG'], ['Nathaniel Smith', '../static/Prefrosh/SmithNathaniel.JPG'], ['Reimond Costa', '../static/Prefrosh/CostaReimond.JPG'], ['Sharne Sun', '../static/Prefrosh/SunSharne.JPG'], ['Dan Rostovtsev', '../static/Prefrosh/RostovtsevDaniel.JPG'], ['Davis Tardif', '../static/Prefrosh/TardifDavis.JPG'], ['Roby Joseph', '../static/Prefrosh/JosephRoby.JPG']]

def returnDayInfo(day):

    if day == "dinnerA":
        return ("Dinner A", dinnerA)

    elif day == "dinnerB":
    	return ("Dinner B", dinnerB)

    elif day == "dinnerC":
        return ("Dinner C", dinnerC)

    elif day == "linnerD":
        return ("Linner D", linnerD)

    elif day == "dinnerE":
        return ("Dinner E", dinnerE)

    elif day == "linnerF":
        return ("Linner F", linnerF)

    elif day == "dinnerG":
        return ("Dinner G", dinnerG)

    elif day == "dinnerH":
        return ("Dinner H", dinnerH)

    elif day == "dessert1":
        return ("Dessert 1", dessert1)

    elif day == "dessert2":
        return ("Dessert 2", dessert2)

    elif day == "dessert3":
        return ("Dessert 3", dessert3)

    elif day == "dessert4":
        return ("Dessert 4", dessert4)

    elif day == "dessert5":
        return ("Dessert 5", dessert5)

    elif day == "dessert6":
        return ("Dessert 6", dessert6)

    elif day == "dessert7":
        return ("Dessert 7", dessert7)